# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: iera-backend/Gateway/Gateway/Dockerfile
    ports:
      - 32770:32770
  
  announcements:
    image: announcements
    build: 
      context: .
      dockerfile: iera-backend/Announcements/Announcements/Dockerfile
    ports:
      - 32772:32772

  users:
    image: users
    build: 
      context: .
      dockerfile: iera-backend/Users/Users/Dockerfile
    ports:
      - 32776:32776

  comments:
    image: comments
    build: 
      context: .
      dockerfile: iera-backend/Comment/Comments/Dockerfile
    ports:
      - 32778:32778
