# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  announcements:
    image: announcements
    build:
      context: .
      dockerfile: iera-backend/Announcements/Announcements/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 32772:32772
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
