apiVersion: apps/v1
kind: Deployment
metadata:
  name: announcements
spec:
  replicas: 3
  selector:
    matchLabels:
      app: announcements
  template:
    metadata:
      labels:
        app: announcements
    spec:
      containers:
      - name: announcements
        image: niceonion/ierasite:announcements-latest
        ports:
        - containerPort: 32772
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
