version: '3.8'
services:
  gateway:
    build:
      context: .
      dockerfile: Gateway/Gateway/Dockerfile
    ports:
      - "8000:80"
  events:
    build:
      context: .
      dockerfile: Events/Events/Dockerfile
  announcements:
    build:
      context: .
      dockerfile: Announcements/Announcements/Dockerfile
