name: CD-pipeline

on:
  workflow_run:
    workflows: ["CI-Backend"]
    types: 
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Compose
      run: docker-compose -v

    - name: Build the Docker images with docker compose
      run: docker-compose up -d

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN_RW }}

    - name: Tag and Push gateway
      run: |
        docker tag gateway:latest niceonion/ierasite:gateway-latest
        docker push niceonion/ierasite:gateway-latest

    - name: Tag and Push announcement
      run: |    
        docker tag announcements:latest niceonion/ierasite:announcements-latest
        docker push niceonion/ierasite:announcements-latest
    
    - name: Tag and Push users
      run: |    
          docker tag users:latest niceonion/ierasite:users-latest
          docker push niceonion/ierasite:users-latest

  deploy:
    runs-on: ubuntu-latest
    needs: build    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'
        
      - name: Deploy to Kubernetes
        run: |
            kubectl apply -f k8s/deployments/deployment-announcements.yaml
            kubectl apply -f k8s/deployments/deployment-users.yaml
            kubectl apply -f k8s/services/announcements.yaml
            kubectl apply -f k8s/services/users.yaml
            kubectl apply -f k8s/ingress.yaml
            kubectl apply -f k8s/hpa/hpa-announcements.yaml
            kubectl apply -f k8s/hpa/hpa-users.yaml