name: CI-Backend

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [6.0.x]
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Set Directory
      run: cd iera-backend/Gateway

    - name: Restore dependencies
      run: | 
        cd iera-backend/Gateway
        dotnet restore

    - name: Build solution
      run: |
        cd iera-backend/Gateway
        dotnet build --no-restore --configuration Release

    - name: Run tests
      run: |
        cd iera-backend/Gateway
        dotnet test --no-build --verbosity normal --configuration Release

    - name: Publish services
      run: |
        cd iera-backend/Gateway
        for project in Announcements Events Gateway; do
          dotnet publish $project/$project/$project.csproj -c Release -o publish/$project
        done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: published-services
        path: iera-backend/Gateway/publish/**/*
