name: Containerization

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Compose
      run: docker-compose -v

    - name: Build the Docker images with docker compose
      run: docker-compose up -d

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN_RW }}

    - name: Tag and Push Docker images to Docker Hub
      run: |
        docker tag gateway:latest niceonion/ierasite:gateway_latest
        docker push niceonion/ierasite:gateway_latest
        docker tag announcement:latest niceonion/ierasite:gateway-latest
        docker push niceonion/ierasite:announcement-latest
